name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm, arm64]
    steps:
    

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Publish Docker
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      with:
        name: kaij/redis_exporter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        extra_build_params: --build-arg GOARCH=${{ matrix.goarch }}
        dockername_appendix: -${{ matrix.goarch }}
